### ISSUE TITLE
Download framework sample code

### ISSUE THREAD

**Issue by asaf** [crossid/crossidio#29]
We should try to make the _Download_ button download a configured version according to user's application configuration.

This requires:

- [ ] Create an endpoint (nextjs has support for endpoints out of the box) that will fetch code of a public git repo
- [ ] Replace relevant vars in some files according to tenant & application in context
- [ ] Compress the files into a zip file
- [ ] Make the browser download the zip by integrating into the _Framework_ page _Download_ button.

The download button should:
- Check if user has configured an app, if yes, send the relevant params to the endpoint and expect a file to be downloaded.
- If user has not configured fields, it'll open a modal, asking for the application configuration, then send the request to the endpoint and expect a file to be downloaded.

The user should then unzip the file, start the sample and it should work as is without any further configuration.

References:
- https://nextjs.org/docs/api-routes/introduction

**Comment by ErezSha** [comment]
@asaf 
It won't work out of the box because the user would still have to create a cidUser and a user inside the app (or just a cid user if we put the app inside everyone role)

**Comment by asaf** [comment]
The sample should have a signup option..
