### ISSUE TITLE
Configure app component

### ISSUE THREAD

**Issue by asaf** [crossid/crossidio#31]
A component that let the user configure (select/create) an application directly from the documentation section.

This required:

- [x] A token that can interact with management
- [x] Possibly issues with CORS as management is in another domain

**Comment by ErezSha** [comment]
redirect uri
logout uri
cors

**Comment by asaf** [comment]
@ErezSha attached is a mocked styled UI with state and everything for selecting/updating an existing app

Still missing:

- [ ] Create UI (I wasn't sure if to separate to another component or you want it to be on the same one)
- [ ] Integration with backend

**Comment by asaf** [comment]
@ErezSha please rebase any new work on top of `draft/mgmtIntegration` it has already the tenant picker styled.
