### ISSUE TITLE
auth does not return to the original page

### ISSUE THREAD

**Issue by asaf** [crossid/crossidio#44]
auth always return to "/" instead of current location

**Comment by asaf** [comment]
@ErezSha this is working but I reopened this coz the behaviour is annoying, it shows the home page first and then after while it directs back to the original page.

**Comment by ErezSha** [comment]
@asaf I'm not sure what you want me to do. That's React + Crossid-React.

**Comment by asaf** [comment]
if that's how it works I'll revise the entire library and its way of redirecting because this looks ugly
